### ISSUE TITLE
Chisel compiler not catching value-less UInt declaration

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/chisel3#271] opened 2016-08-31 06:25 UTC
This is probably easier to explain with an example. If you accidentally did the following

    val foo = Reg(init = UInt(width = 8))

Instead of

    val foo = Reg(UInt(width = 8))

Chisel will happily pass it through and then FIRRTL will give an error message like

    Exception in thread "main" firrtl.passes.CheckChirrtl$UndeclaredReferenceException$1: : [module DmaTestDriver] Reference T_653 is not declared.

Not sure if this is a Chisel or FIRRTL bug. But somewhere along the line, it should detect that you are using a UInt that isn't given a value and print out the proper Scala line number.

**Comment by ucbjrl** [comment] 2016-08-31 15:21
This is caught by Stephen's connection checks in the gsdt branch to be discussed in today's Chisel meeting.

**Comment by ben-k** [comment] 2016-08-31 19:13
This is a duplicate of #230 - perhaps close one or the other?

**Closed** 2016-08-31 23:59 UTC
