### ISSUE TITLE
Seq->Vec bulk connection issue leads to unintuitive (incorrect?) semantics

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel3#286] opened 2016-09-20 23:52 UTC
**Scenario:**
- I have a Seq of Modules that I assign some inputs to.
- I then create a Vec of the IOs of these Modules so I can assign dynamically more inputs to them.
- The inputs assigned to the Seq are no longer honored. 

``` scala
val tables = for (i <- 0 until num_tables) yield { val table Module(...); ...; table }
tables.map{_.io.allocate.valid := Bool(false) } // this assignment is left unconnected!
val tables_io = Vec(tables.map(_.io))
tables_io.map{_.allocate.valid := Bool(false)} // this assignment succeeds!
```

Notice that nowhere did I invoke the bulk connection operator.

---

**Theory:** 

Jack's theory is the Vec.apply() that accepts a Seq is creating a Wire that kicks in the bulk connection semantics, and blows away all of my previous input assignments.

---

**Problem:** 
- Code that worked in Chisel2 no longer works in Chisel3. 
- Resulting behavior is very unintuitive, and possibly wrong.

---

**To Test:**

The full code can be found here (https://github.com/ucb-bar/riscv-boom/blob/master/src/main/scala/tage.scala#L187).

Checkout boom (http://ucb-bar.github.io/riscv-boom/), but before building, set TageKey, `enabled` to true in (/scratch/celio/boom-chip/boom/src/main/scala), and the GShareKey's `enabled` to false.

---

**Workaround:**

Only ever write to the `tables_io` construct.

**Comment by ucbjrl** [comment] 2016-09-21 00:06
This may be fixed in the gsdt branch. The problem is the current `Vec.do_apply( )` method invokes the following code:

    val maxWidth = elts.map(_.width).reduce(_ max _)
    val vec = Wire(new Vec(t.cloneTypeWidth(maxWidth), elts.length))
    for ((v, e) <- vec zip elts)
      v := e
    vec

This effectively performs one-way connections to the Vec elements.

The equivalent gsdt code is:

    val maxWidth = elts.map(_.width).reduce(_ max _)
    val vec = Wire(new Vec(t.cloneTypeWidth(maxWidth), elts.length))
    def doConnect(sink: T, source: T) = {
      if (elts.head.flatten.exists(_.firrtlDirection != Direction.Unspecified)) {
        sink bulkConnect source
      } else {
        sink connect source
      }
    }
    for ((v, e) <- vec zip elts) {
      doConnect(v, e)
    }
    vec

**Closed** 2017-02-06 21:27 UTC
